spring.application.name=estud-io-api
server.port=8080
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.flyway.url=
spring.flyway.user=
spring.flyway.password=
logging.level.org.springframework.security=ERROR
jwt.secret=

spring.mail.host=
spring.mail.port=
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=
spring.mail.properties.mail.smtp.starttls.enable=
spring.mail.from=
